# Generated by Django 2.0.5 on 2018-06-13 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hlasovani', '0002_auto_20180610_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kandidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vitezove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kandidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hlasovani.Kandidat')),
            ],
        ),
        migrations.RenameField(
            model_name='datafile',
            old_name='name',
            new_name='nazev',
        ),
        migrations.RenameField(
            model_name='datafile',
            old_name='data',
            new_name='soubor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='votes',
        ),
        migrations.AddField(
            model_name='datafile',
            name='konec_hlasovani',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datafile',
            name='konec_kandidovani',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='token',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kandidat',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hlasovani.Student'),
        ),
    ]
